### ISSUE TITLE
Uncaught TypeError: div.prop is not a function

### ISSUE THREAD

**Issue by alexindigo** [JsonHunt/save-commands#28]
After applying fix for #25, following happened:

[Enter steps to reproduce below:]
1. Edit a file
2. Hit save

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [save-commands](https://github.com/JsonHunt/save-commands) package, v0.6.2
### Stack Trace

Uncaught TypeError: div.prop is not a function

```
At /Users/alex/.atom/packages/save-commands/lib/atom-save-commands.coffee:114

TypeError: div.prop is not a function
    at Socket.<anonymous> (/Users/alex/.atom/packages/save-commands/lib/atom-save-commands.coffee:114:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
### Commands

```
     -0:27.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:26.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:25.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:18.3.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:15.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:03.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "minimap"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
atom-alignment, v0.12.1
atom-beautify, v0.28.19
atom-html-preview, v0.1.13
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
docblockr, v0.7.3
editorconfig, v1.2.2
file-icons, v1.6.13
language-docker, v1.1.6
linter, v1.11.3
linter-eslint, v5.2.6
markdown-preview-plus, v2.2.2
project-manager, v2.6.5
red-wavy-underline, v0.3.0
remote-sync, v3.5.0
save-commands, v0.6.2
symbols-tree-view, v0.11.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by alexindigo** [comment]
Same happens on line `124`.

**Comment by marc1n** [comment]
+1

**Comment by JsonHunt** [comment]
fixed
