### ISSUE TITLE
Failed to load the save-commands package

### ISSUE THREAD

**Issue by petemill** [JsonHunt/save-commands#4]
[Enter steps to reproduce below:]
1. Install latest save-commands
2. Open Atom

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [save-commands](https://github.com/JsonHunt/save-commands) package, v0.5.0
### Stack Trace

Failed to load the save-commands package

```
At Cannot find module 'win-spawn'

Error: Cannot find module 'win-spawn'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/petemill/.atom/packages/save-commands/lib/atom-save-commands.coffee:5:9)
  at Object.<anonymous> (/Users/petemill/.atom/packages/save-commands/lib/atom-save-commands.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:51:25)

```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "sass-watch"
    ],
    "projectHome": "/Development/",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "destroyEmptyPanes": false
  },
  "save-commands": {}
}
```
### Installed Packages

``` coffee
# User
atom-macros, v0.5.0
autoclose-html, v0.15.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.6.0
color-picker, v1.5.0
project-manager, v1.15.5
save-commands, v0.5.0
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by JsonHunt** [comment]
It was caused by missing dependency in package.json. Try the new version, I added the ability to run save commands on folders (recursive)
