### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by rgwch** [JsonHunt/save-commands#9]
[Enter steps to reproduce below:]
1. just installed and hit shift-command-P -> save command -> Execute on

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [save-commands](https://github.com/JsonHunt/save-commands) package, v0.6.1
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:817

TypeError: path must be a string
  at TypeError (native)
  at fs.lstat (fs.js:819:11)
  at Object.fs.lstat (ATOM_SHELL_ASAR.js:187:16)
  at Object.module.exports.AtomSaveCommands.getFilesOn (/Users/name/.atom/packages/save-commands/lib/atom-save-commands.coffee:263:6)
  at /Users/name/.atom/packages/save-commands/lib/atom-save-commands.coffee:245:5
  at /Users/name/.atom/packages/save-commands/lib/atom-save-commands.coffee:231:4
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:302:5)

```
### Commands

```
     -0:55.2 editor:indent (atom-text-editor.editor.is-focused)
     -0:45.6 editor:newline (atom-text-editor.editor.is-focused)
     -0:45.3 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:45.3 snippets:expand (atom-text-editor.editor.is-focused)
     -0:45.3 editor:indent (atom-text-editor.editor.is-focused)
     -0:39.8 editor:newline (atom-text-editor.editor.is-focused)
     -0:32.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:30.7 core:save (atom-text-editor.editor.is-focused)
     -0:26.8 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:23.7 core:confirm (atom-text-editor.editor.mini)
     -0:23.7 save-commands:executeOn (atom-text-editor.editor.is-focused)
     -0:17.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.9 core:save (atom-text-editor.editor.is-focused)
     -0:08.1 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:04.3 core:backspace (atom-text-editor.editor.mini)
     -0:00.8 save-commands:executeOn (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-jade, v0.4.0
linter, v0.12.0
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-jshint, v0.1.2
linter-less, v0.3.1
save-commands, v0.6.1

# Dev
No dev packages
```

**Comment by rgwch** [comment]
The problem was: I had commands like this:
"src/main/*_/_.jade: npm run compile:jade"

When I changed the script name to "compile-jade" it works. Sorry for the issue report.
